#!/usr/bin/env bash

set -euo pipefail

acai skill --install

AGENT="assist"
AGENTS_DIR=".claude/agents"
SETTINGS=".claude/settings.json"
LOCK="devenv.lock"
WORKFLOW_AGENTS=(supervise prepare-tasks implement review-task)

# Every check names the full ACID of the requirement it validates.
fail() {
  echo "FAIL [$1] $2" >&2
  exit 1
}

pass() {
  echo "ok   [$1] $2"
}

# Print the YAML frontmatter of a generated agent definition.
frontmatter() {
  awk 'NR == 1 && $0 == "---" { inside = 1; next }
       inside && $0 == "---" { exit }
       inside { print }' "$1"
}

frontmatter_has() {
  frontmatter "$1" | grep -qxF "$2"
}

echo "=== claude-agents: querying the generated agent definitions ==="

# 1. The example was evaluated against the modules in this checkout.
#
# generic-agent.HARNESS.1
# devenv.lock records how the `devenv` module input was resolved, and it is
# written before this script runs because the shell cannot be built without it.
# Two local forms are legitimate: devenv-run-tests injects `git+file:` to this
# checkout when it runs us inside the devenv shell, while a plain `devenv test`
# in this directory resolves devenv.yaml's relative `../..` path instead. Any
# other source means the example ran against the published modules — as it
# would if this script nested another `devenv shell`, or if the harness stopped
# running us inside one — and then every check below is asserting on artefacts
# generated by the wrong code. So this check runs first.
if [ ! -e "$LOCK" ]; then
  echo "Contents of $PWD:" >&2
  ls -la >&2 || true
  fail generic-agent.HARNESS.1 "$LOCK does not exist, so the resolved 'devenv' module input cannot be verified"
fi

# Emit the resolved `devenv` input on three lines: its type, its dir, and the
# local path it points at (empty when the source is not local).
devenv_input=$(node -e '
  const fs = require("fs");
  const lock = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
  const ref = ((lock.nodes[lock.root] || {}).inputs || {}).devenv;
  const key = Array.isArray(ref) ? ref[ref.length - 1] : ref;
  const locked = (lock.nodes[key] || {}).locked || {};
  const url = locked.url || "";
  let local = "";
  if (locked.type === "path") local = locked.path || "";
  else if (locked.type === "git" && url.startsWith("file:")) local = url.replace(/^file:(\/\/)?/, "");
  process.stdout.write([locked.type || "missing", locked.dir || "", local].join("\n") + "\n");
' "$LOCK")
{
  IFS= read -r input_type
  IFS= read -r input_dir
  IFS= read -r input_path
} <<<"$devenv_input" || true
input_type=${input_type:-unreadable}

repo_root=$(cd ../.. && pwd -P)
input_root=""
if [ -n "$input_path" ]; then
  input_root=$(cd "$input_path" 2>/dev/null && pwd -P) || input_root=""
fi

if [ "$input_root" != "$repo_root" ] || [ "$input_dir" != "src/modules" ]; then
  echo "Contents of $LOCK:" >&2
  cat "$LOCK" >&2
  fail generic-agent.HARNESS.1 "the 'devenv' module input resolved to a '$input_type' source at '${input_path:-<not local>}' (dir: '$input_dir'), expected the modules of this checkout at '$repo_root' (dir: 'src/modules')"
fi
pass generic-agent.HARNESS.1 "the example was evaluated against the modules of this checkout: '$input_type' source at $repo_root, dir 'src/modules'"

# generic-agent.TESTS.1
# The agent, in devenv terms, is the definition the claude module generates.
# The checks below query that definition directly; they never call out to
# Claude, so they need no credentials and stay deterministic in CI.

# 2. The agent is registered.
agent_file="$AGENTS_DIR/$AGENT.md"
if [ ! -e "$agent_file" ]; then
  echo "Contents of $AGENTS_DIR:" >&2
  ls -la "$AGENTS_DIR" >&2 || true
  fail generic-agent.TESTS.1 "agent '$AGENT' is not registered: $agent_file does not exist"
fi
pass generic-agent.TESTS.1 "agent '$AGENT' is registered at $agent_file"

# 3. It is not the primary agent.
if [ ! -e "$SETTINGS" ]; then
  fail generic-agent.TESTS.1 "$SETTINGS does not exist"
fi
# `|| true` keeps an unmatched grep from aborting the script under `set -euo
# pipefail`, so the empty-value branch below stays reachable and reports why.
primary=$(grep -o '"agent"[[:space:]]*:[[:space:]]*"[^"]*"' "$SETTINGS" | head -n 1 | sed 's/.*"\([^"]*\)"$/\1/' || true)
if [ -z "$primary" ]; then
  echo "Contents of $SETTINGS:" >&2
  cat "$SETTINGS" >&2
  fail generic-agent.TESTS.1 "no primary agent recorded in $SETTINGS"
fi
if [ "$primary" = "$AGENT" ]; then
  fail generic-agent.TESTS.1 "agent '$AGENT' is the primary agent in $SETTINGS, it must not be"
fi
if [ "$primary" != "supervise" ]; then
  fail generic-agent.TESTS.1 "expected the primary agent in $SETTINGS to be 'supervise', found '$primary'"
fi
pass generic-agent.TESTS.1 "agent '$AGENT' is not primary; the primary agent is '$primary'"

# 4. It is distinct from the four workflow agents, which are all still intact.
for workflow_agent in "${WORKFLOW_AGENTS[@]}"; do
  if [ "$AGENT" = "$workflow_agent" ]; then
    fail generic-agent.TESTS.1 "agent '$AGENT' must not be one of the workflow agents"
  fi

  workflow_file="$AGENTS_DIR/$workflow_agent.md"
  if [ ! -e "$workflow_file" ]; then
    fail generic-agent.TESTS.1 "workflow agent '$workflow_agent' is missing: $workflow_file does not exist"
  fi
  if ! frontmatter_has "$workflow_file" "name: $workflow_agent"; then
    fail generic-agent.TESTS.1 "workflow agent '$workflow_agent' no longer declares 'name: $workflow_agent'"
  fi
done
pass generic-agent.TESTS.1 "agent '$AGENT' is distinct from ${WORKFLOW_AGENTS[*]}, which are all still present"

# 5. Its tools grant the capabilities of the generic agent.
# generic-agent.EXAMPLES.1
for tool in Read Grep Glob Bash WebFetch; do
  if ! frontmatter_has "$agent_file" "  - $tool"; then
    echo "Frontmatter of $agent_file:" >&2
    frontmatter "$agent_file" >&2
    fail generic-agent.EXAMPLES.1 "agent '$AGENT' is not granted the '$tool' tool"
  fi
done
for tool in Write Edit; do
  if frontmatter_has "$agent_file" "  - $tool"; then
    fail generic-agent.EXAMPLES.1 "agent '$AGENT' is granted the authoring tool '$tool', which belongs to the 'implement' agent"
  fi
done
pass generic-agent.EXAMPLES.1 "agent '$AGENT' is granted Read, Grep, Glob, Bash and WebFetch, and no authoring tools"

echo "=== claude-agents: all checks passed ==="
